spring:
  application:
    name: ashram-donation-management
  main:
    web-application-type: none

aws:
  region: ${AWS_REGION_OVERRIDE:ap-south-1}
  dynamodb:
    tables:
      donors: ${AWS_DYNAMODB_TABLES_DONORS:ngo-donors}
      donations: ${AWS_DYNAMODB_TABLES_DONATIONS:ngo-donations}
  ses:
    sender-email: ${AWS_SES_SENDER_EMAIL:chaitanyakonge2002@gmail.com}
